mariadb:
  type: mariadb:10.11
  disk: 1024
  configuration:
    properties:
      default_charset: utf8mb4
      default_collation: utf8mb4_unicode_ci
    schemas:
      - sagwa
    endpoints:
      admin:
        default_schema: sagwa
        privileges:
          sagwa: admin

